name: Publish Docker to GPR
on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Build, Tag, Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: docker.pkg.github.com/${{ github.repository }}/hakyll-latex
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_names: true
        cache: true
